### ISSUE TITLE
Week 2: Index all the words

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#12]
Currently the code skips stop words and potentially other ones. Index everything

**Comment by rrimpila** [comment]
I had a quick try, there is a parameter stop_words, which when passed None should not use the default stopwords list. Didn't test this though, and it still seems to ignore "a" at least.

**Comment by ciccmin** [comment]
It seems to work! Except for "a". I initially thought changing the parameter to None did nothing to the code, but now I realise it simply (for some reason) ignores the only word I had used as tester, which is "a" as you said

**Comment by tiigit** [comment]
@rrimpila @ciccmin We seem to be content with this even though we can't search for one-letter-words? This concerns also the word "I" for example. But I at least don't know how to tackle this issue...

**Comment by rrimpila** [comment]
I found it, there's a token_pattern parameter, which by default is r'(?u)\b\w\w+\b'. So by removing the \w requirement we'll find also the one-letter words, I believe

**Comment by tiigit** [comment]
Ohh, that was it! Now it works. I added to the user query instructions, which are printed when the program is run, that all search words need to be in lowercase letters, as I forgot that myself and tried to find the word "I" and wondered why it didn't work :D
