### ISSUE TITLE
Week 2: Showing Results

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#14]
The program should print the contents of retrieved documents. If there are more than N documents retrieved, print the total number and only the M first documents. If a document contains more than X words, print only the first Y words from a document.

**Comment by tiigit** [comment]
In this last version, which is the file tp_test_boolean.py, I simplified the error handling part (since all the matching documents are already handled in the "try" part of the test_query() function). If this looks good to you @rrimpila @ciccmin , we could go with this? :)

**Comment by rrimpila** [comment]
Yes, looks cleaner. I simplified the results printing a bit, we don't have to limit the results in a loop, we can get the first ten items of the list with hits_list[:10] and the first 1000 characters of the document with documents[doc_idx][:1000].

**Comment by tiigit** [comment]
Thank you @rrimpila ! That looks great :) I will close this issue now
