### ISSUE TITLE
Refine search: stemming

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#17]
Your search engine will not only find documents, in which your search terms are exact matches, but other inflected forms will match as well. For instance, if you work on English data, a search for house will find documents containing house, houses, housing etc. Similarly a search for houses will return the same documents.

**Comment by ciccmin** [comment]
The nltk snowball stemming feature might be helpful!

https://www.nltk.org/api/nltk.stem.snowball.html

**Comment by ciccmin** [comment]
used the snowball stemmer. Found an issue where it wouldn't stem words in the comparative (-er, -est) form. Cannot figure out yet how to fix it, but for now we have a stemmer.

**Comment by ciccmin** [comment]
Also added a function that stems documents

**Comment by ciccmin** [comment]
Consider: instead of stemming the whole document, look for all possible words that share a stem with the query

**Comment by ciccmin** [comment]
Think I'm done with this and #18 . @tiigit @rrimpila can you review? :D
