### ISSUE TITLE
Refine search: stemming and exact match

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#18]
Probably should not be worked at before #17
Support both stemming and exact matches. For instance, you could run exact matching on terms enclosed in double quotes, such as "house", and stemming on terms without quotes, such as house. You could either expect the whole query to be of either type or you could allow a mix of both types in one single query, such as clean "house".

**Comment by ciccmin** [comment]
What I did when working with #17 tackled part of this issue and I forgot to tag it. Currently there are two detected issues that I'll attempt to tackle:
1. stemming the word "house" produces "hous", resulting in 0 search results in both search types;
2. quotation marks produce errors in boolean search.
