### ISSUE TITLE
Refine search: Multi-word phrases

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#19]
Often it is useful to find contiguous phrases of words rather than just words anywhere in a document. A user searching for "New York" may not expect to find documents where new and York both occur, but separately. You could support phrases either as exact matches or with stemming. There are multiple ways of solving this. You can look at the documentation of the [CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) and [TfidfVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) to get some ideas. You can also come up with your own approach.

**Comment by tiigit** [comment]
If we decide to work on this enhancement, maybe we'll want to approach this so that when the user wants to find multi-word phrases, the words would have to be typed to the query inside quotation marks "". And our search engine would then recognize that these are the words that want to be found together. So the user query would be: "New York", instead of: New York.

**Comment by tiigit** [comment]
Hello, I didn't have any more time to solve this issue, so if either of you want to keep working on this, it would be nice :) @rrimpila @ciccmin 

Where we are now is that in the Ranking search engine, I have separated search queries that have multi-word phrases (the search queries that have quotation marks at the start and the end of the query) into it's own elif-condition. So what should be done next is to resolve how to handle those cases in the ranking_search() as two consecutive words and not as two separate words.

We could also add this multi-word search query functionality into the Boolean search engine.

**Comment by rrimpila** [comment]
I think it's a parameter, ngram_range, that allows supporting multiple words up to some limit. I'm testing if that does what I expect it to.
High limits may be detrimental to the performance, the dictionary will grow to huge sizes. So maybe up to 2 or 3 words?

**Comment by tiigit** [comment]
Ah right, I didn't realize there is a ready parameter for that 😅 I think 3 words would be good, if it doesn't make the engine too slow (if that doesn't work well we can go also with 2 words).

**Comment by rrimpila** [comment]
I have a working version of the exact matching. I made it support also unigrams, so that if we get stemming to work, it will support that for exact matching. The solution for ranked search feels a bit heavy, since it creates a Vectorizer for each length of grams, to be sure to match only that length. 

Boolean search was simpler (just not splitting quoted text), but it will require additional work to be compatible with stemming

**Comment by rrimpila** [comment]
Having looked into this, I haven't found a simple solution that would lessen the need for preprocessing. Given that we can set it up so that it is only done once when the application starts, I think I'll leave this as is for now.
