### ISSUE TITLE
Combine Boolean search and relevance ranking

### ISSUE THREAD

**Issue by tiigit** [rrimpila/tiramisu#22]
Try to include both search engines (Boolean and relevance ranking) in the same program and ask the user which one to use. Or have your program automatically check whether there are any Boolean operators in the query, and in that case run Boolean search, otherwise tf-idf based search.

**Comment by tiigit** [comment]
I combined the two search engines and let the user decide which one to use. I personally think it looks pretty neat and works kinda nicely, could you please test and review? :) @ciccmin @rrimpila

**Comment by tiigit** [comment]
I also send you a couple messages on Slack (regarding this and some other things), so here is a notification just in case you don't get notifications :D @rrimpila @ciccmin

**Comment by ciccmin** [comment]
Everything is good and works! 
To optimize this it might be good to add a "go back" function for the user to navigate between ranking and boolean search instead of having to close and reopen the program every time. But it's something additional that came to mind while using it and it's not needed for this week's task :D

**Comment by tiigit** [comment]
I thought about that too! Just couldn't figure out a way to do it yet (because I don't think I can call the main function in the boolean_search or ranking_search functions so that the main program would start over and user could choose again...). But I like the challenge, let me see if I can solve this and make it happen during next week :D

**Comment by rrimpila** [comment]
You could make the choice not break the loop, so once the user inputs an empty string within one of the search options, it will exit to the outer while loop. Then user would need to enter empty string twice to close it completely, but it might be still reasonable

**Comment by tiigit** [comment]
Right that's true! Thanks! I'll try that :)

**Comment by tiigit** [comment]
Got it!
