### ISSUE TITLE
Modify how the search engine results are shown

### ISSUE THREAD

**Issue by tiigit** [rrimpila/tiramisu#23]
I will change some things that we discussed in class about how the results will be shown to the user (e.g. not showing all 1000 characters but less).

**Comment by rrimpila** [comment]
This is probably not necessary for the web UI (or has a different implementation there), we discussed adding a read more feature in #26 so that the whole document can be presented but it is initially only shown partially.

**Comment by tiigit** [comment]
Yeah sure that sounds good. I still thought I could improve how the search engine works on the command line as well.

**Comment by tiigit** [comment]
@rrimpila @ciccmin I'm now ready with this issue and content on how the program looks on terminal. If you guys want to review or make some changes, just go for it :)
