### ISSUE TITLE
Make a search engine

### ISSUE THREAD

**Issue by ciccmin** [rrimpila/tiramisu#24]
Make (some version of) your search engine run in a web UI.
When the server application starts, it should index your data. The search interface should be embedded in web pages. You need HTML/Jinja templates for this.
All interaction should take place in the browser. The user should be able to enter the input and the search results should be displayed on a web page.

**Comment by rrimpila** [comment]
I believe the basic functionality is now working, it searches and gives results. And error messages are also displayed

**Comment by rrimpila** [comment]
Closing for clarity, open new tickets if more functionality needed
