### ISSUE TITLE
Search engine layout

### ISSUE THREAD

**Issue by ciccmin** [rrimpila/tiramisu#25]
It does not hurt, if the web page looks nice as well. Maybe you want to have some image, or logo, or nice fonts?

**Comment by rrimpila** [comment]
Maybe add nicely formatted instructions within this as well

**Comment by tiigit** [comment]
I still need to fix some things regarding how our webpage looks/works. E.g. to show instructions only for the chosen search engine based on which radio button the user selects and to show results also based on selected engine (because boolean search doesn't have relevance score).

**Comment by rrimpila** [comment]
Closing for clarity, open new tickets if more functionality needed/considered

**Comment by rrimpila** [comment]
Added the functionality to show correct instructions immediately on page load
