### ISSUE TITLE
Search engine layout — "Read more" feature

### ISSUE THREAD

**Issue by ciccmin** [rrimpila/tiramisu#26]
Whenever the user wants to read the full document, allow them to open it with a "read more" button

**Comment by ciccmin** [comment]
This might be useful https://www.w3schools.com/howto/howto_js_read_more.asp

**Comment by rrimpila** [comment]
Added buttons and some styling for read more. Still missing detection if the whole article fits in the limits, and thus doesn't need the button.

**Comment by tiigit** [comment]
Looks good! Read more button works well.

**Comment by rrimpila** [comment]
Added logic to only create read more button for documents with longer content. And changed max-height to only required height to limit animation stutter.
