### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#34]
Current readme is only copied from the demo and modified to fit our filename. It should be a bit more specialised and at least explain the app briefly. The variables should be set for the final product we return, so this needs to be done near the completion of the project.

Should we list the imported modules the user might need to install? If we get #35 done, we only need to refer to running that.

**Comment by tiigit** [comment]
#35 requirements.txt created!

**Comment by rrimpila** [comment]
I can write the instructions on how to run the application, but could each member note if they have some functionality or features they feel like highlighting
