### ISSUE TITLE
Emphasize query words within document

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#37]
Bold? Emphasis? Background-colour

**Comment by tiigit** [comment]
Emphasize in some way (italics, bold, something else?) that's not highlighting. We'll highlight named entities with SpaCy (#44 ), so make sure search words pop out from the text.

**Comment by tiigit** [comment]
This emphasizing should work now for texts not processed by spaCy. Would you test if you find some problems @rrimpila @ciccmin ?

Ps. Also I'll gladly take hints or hear suggestions on how to make this work together with spaCy (I've done testing but can't figure out how to do both at the same time).

**Comment by rrimpila** [comment]
It seems to be working nicely. 
What kind of trouble are you having in conjunction with spaCy? It looks like you should be able to utilise the same functionality even on spacied content (as long as you do it after the spaCy handling, since that escapes html, if I recall correctly)

**Comment by tiigit** [comment]
@rrimpila you're right! I tested the code that emphasizes query words with spacy again, and now it works :D I think I forgot something from my code in my earlier tests. But anyways, I'll clean my code up and push the changes soon.

**Comment by tiigit** [comment]
Okay now this should work!
I'm now finished with this issue. If you notice something that should be modified, let me know @rrimpila @ciccmin :)
