### ISSUE TITLE
Data scraping: search limiting

### ISSUE THREAD

**Issue by ciccmin** [rrimpila/tiramisu#39]
Scrape data from source material (works, users, publishing date etc). Limit search somehow (200 most relevant for every year in the last five years?)

**Comment by ciccmin** [comment]
The webpage api may come in handy: https://pypi.org/project/ao3-api/

**Comment by ciccmin** [comment]
Ditched the previously-mentioned api for this package that suits our needs better 

https://github.com/alexwlchan/ao3

**Comment by tiigit** [comment]
Limiting data to 100 articles per year for 5 years (= 500 articles in total).
