### ISSUE TITLE
Plots: Highlighting named entities with spaCy

### ISSUE THREAD

**Issue by tiigit** [rrimpila/tiramisu#44]
Include to the code visualization using spaCy.

**Comment by tiigit** [comment]
Highlighting works when not too many matches are found (e.g. when using query: abortion), but spaCy processing is very slow, so program crashes if too many matches are found. This needs fixing still.

Also an idea: spaCy highlighting is possible to do so that spaCy only displays chosen entities (e.g. all the person entities). We should consider choosing only some specific named entities for our final project, because otherwise the document texts will be full of highlighting.

Let me know if you have ideas regarding this issue! :) @rrimpila @ciccmin

**Comment by ciccmin** [comment]
Works great!!
