### ISSUE TITLE
Plots: time/quantity/tag type graph

### ISSUE THREAD

**Issue by ciccmin** [rrimpila/tiramisu#47]
Use MatPlotLib to create a graph that shows the amount of times a specific tag type is used in works posted in the span of five years.
The x-axis will show the time of posting, y will represent the amount of tags and colours will differentiate between different tag types.

**Comment by ciccmin** [comment]
Yaho! I finished working on this. What do you think, @tiigit @rrimpila ? If you encounter bugs or would suggest changes I'm open for anything!

Currently I deem the marker size a bit too small whenever the amount of matches is little, but have yet to figure out a way that allows the markers to be big without messing with the values shown in the legend. Do you have any suggestions with that, or should we just leave it as it is?

**Comment by rrimpila** [comment]
I edited the height slightly to match with the other plot.

And I changed the calculation to use the same monthly counting as the other one. The dist_dict isn't then needed, we can use the dates from x to calculate the required width

**Comment by rrimpila** [comment]
I don't think the size of the balls is too bad when they are not as close together. They are on the smaller side, though.

**Comment by tiigit** [comment]
Good job! I think we should make the dots a bit bigger, if it's not a too difficult task. Do you think it would be an easy fix? @rrimpila @ciccmin

**Comment by ciccmin** [comment]
Changing the size would be easy. I'm unsure of how to do it without it affecting the values shown in the graph legend, but I don't think that is too hard, either :D

**Comment by ciccmin** [comment]
Think I'm done with this! I changed the marker size to 3x bigger than before (any bigger and the markers would overlap on bigger search results and made it so the legend shows the right values.  I think we can close this issue now. What do you guys think? @rrimpila @tiigit

**Comment by tiigit** [comment]
Looks better!! We can close this :)
