### ISSUE TITLE
Layout: update instructions (final)

### ISSUE THREAD

**Issue by ciccmin** [rrimpila/tiramisu#48]
After everything else is done, update instructions with basic information regarding the source site the search engine mines data from along with what kind of information can be extracted from it (explain different graphs etc.)

**Comment by tiigit** [comment]
We need to add to relevance ranking search instructions that boolean operators can be used in ranking search as well, and also together with exact match (quotations).

**Comment by ciccmin** [comment]
Same thing as #56: this task is completed, but if we want to make additional changes last-minute it's not a problem
