### ISSUE TITLE
Plots: Highlight only chosen named entities with spaCy

### ISSUE THREAD

**Issue by tiigit** [rrimpila/tiramisu#49]
An idea: spaCy highlighting is possible to do so that spaCy only displays chosen entities (e.g. all the person entities). We should consider choosing only some specific named entities for our final project, because otherwise the document texts will be full of highlighting.

**Comment by tiigit** [comment]
It is also possible to define the colors used in highlighting, let's keep that in mind as well.

**Comment by rrimpila** [comment]
We could provide user with interface to choose which elements are highlighted. Added some checkboxes to demonstrate the idea
