### ISSUE TITLE
Week 1 Your own web page using HTML

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#5]
https://moodle.helsinki.fi/mod/page/view.php?id=3007996

**Comment by tiigit** [comment]
@rrimpila @ciccmin I added/edited a couple of things on the web page. Are we now ready with this task or does anyone hope we would do something more? :)

**Comment by ciccmin** [comment]
I checked it out and it looks great! I think we're ready with this task :D

**Comment by rrimpila** [comment]
Approved
