### ISSUE TITLE
Plots: Show the chronological distribution of retrieved documents in a graph

### ISSUE THREAD

**Issue by rrimpila** [rrimpila/tiramisu#50]

**Comment by rrimpila** [comment]
The graph is now drawn by grouping all the retrieved documents from the same week to the Monday of the week. Otherwise the bars spanning potentially five years didn't fit very well in a single graph. 
The work is mostly done, now it just uses randomly generated dates and I'll fix it to the real dates once we have real data.

**Comment by rrimpila** [comment]
@tiigit @ciccmin Edited the plot to use real dates from the data. If you encounter broken graphs, let me know

**Comment by rrimpila** [comment]
@tiigit @ciccmin I couldn't figure out how to fit data that could span years in any reasonable width, so I edited the graph to extend dynamically and then be scrollable. The visual look is better, but scrolling is obviously a bit bothersome. Opinions?

**Comment by tiigit** [comment]
I think this version looks better! I don't mind the scrolling because at least you can now see the pillars more clearly.
Plus, the user can save the graph as a picture or open it in new tab to see the whole graph at the same time. Also the monthly distribution of results is a good idea.
